- name: Provision Infra and Deploy App
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Terraform up
      terraform:
        project_path: stage_two/terraform
        force_init: yes
        state: present

    - name: Add VM to dynamic inventory
      add_host:
        name: dynamic-vm
        ansible_host: 192.168.100.20
        groups: webservers
        ansible_user: vagrant
        ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
        ansible_python_interpreter: /usr/bin/python3

- import_playbook: ../playbook.yml
