- name: Deploy Application with Ansible
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Show initial config
      debug:
        msg:
          - "App: {{ app_name }}"
          - "Cloning from: {{ repo_url }}"
      tags: ['always']

  roles:
    - role: setup
      tags: ['setup']
    - role: docker
      tags: ['docker']
    - role: database
      tags: ['db']
    - role: backend
      tags: ['api']
    - role: frontend
      tags: ['web']

  post_tasks:
    - name: Validate running containers
      shell: docker ps --format "table {{ '{{.Names}}' }}\t{{ '{{.Status}}' }}"
      register: containers

    - name: Show container status
      debug:
        var: containers.stdout_lines
