- name: Deploy YOLO E-commerce Application with Ansible
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml

  roles:
    - common
    - docker
    - database
    - backend
    - frontend
